import type { Metadata } from "next";
import { Amiri, Cairo, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import localFont from 'next/font/local'
import { cn } from "@/lib/utils"; import { SiteHeader } from "@/components/layout/site-header";
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={cn("h-full scrollbar-thin scrollbar-thumb-primary/10 scrollbar-track-transparent", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, uthmani.variable, amiri.variable, cairo.variable)}
        >
            <body className="@container min-h-full">
                <Provider>
                    <div className=" h-full bg-background">
                        <SiteHeader />
                        {children}
                    </div>
                </Provider>
            </body>
        </html>
    );
}


const uthmani = localFont({
    src: './fonts/uthmani.ttf',
    variable: '--font-uthmani',
})

const cairo = Cairo({
    variable: "--font-cairo",
    subsets: ["latin", "arabic"],
    weight: ["400", "500", "600", "700"],
});

const amiri = Amiri({
    variable: "--font-amiri",
    weight: "400",
    subsets: ["arabic"],
});


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
